---
- hosts: localhost    
  tasks:
    - name: "install ansible galaxy role(s)"
      command: ansible-galaxy install "{{item}}"
      with_items:
        - geerlingguy.docker

- hosts: testing_instance
  roles:
  - role: geerlingguy.docker
    become: yes
    vars:
      docker_edition: 'ce'

- hosts: testing_instance
  roles:
  - role: andrewrothstein.docker-compose
    become: yes
        
- hosts: testing_instance
  roles:
  - role : artifactory-instance-role
    become: yes
    vars:
      docker_compose_source: /root/arghya/nexus-docker-compose.yaml
      docker_compose_destination: /work/
      nexus_service_source: /root/arghya/nexus.service
      nexus_service_destination: /etc/systemd/system/
