---
- hosts: testing_instance
  roles:
  - role : artifactory-instance-role
    become: yes
    vars:
      docker_compose_source: /root/arghya/nexus-docker-compose.yaml
      docker_compose_destination: /work/
      nexus_service_source: /root/arghya/nexus.service
      nexus_service_destination: /etc/systemd/system/
