---
- hosts: cicd-instance
  tasks:
    - name: Install roles from Ansible Galaxy
      shell: ansible-galaxy install "{{ item }}"
      with_items:
        - geerlingguy.java
        - geerlingguy.jenkins
